### ISSUE TITLE
How can I pass the event to the selectMultipleOption method, and not only the value?

### ISSUE THREAD

**Issue by lauracabre** [Aidurber/react-picky#101]
How can I pass the event object to the selectMultipleOption method, and not only the value selected?

**Comment by Aidurber** [comment]
As in return the last selected option?

If so then I don't believe that's possible, the component maintains very little of its own state. All the currently selected options get returned so the developer can pass them back in a props. Picky is a 100% controlled component so the component that is using Picky is the source of truth for the data. 

There are ways but none of them are particularly nice, such as finding what's different from the previous state and the next state i.e. [How to get the difference between two arrays of objects in JavaScript](https://stackoverflow.com/questions/21987909/how-to-get-the-difference-between-two-arrays-of-objects-in-javascript/21988185). But there are performance considerations to be had if you do that approach.
