### ISSUE TITLE
Problem with sellect all work opposite to expected

### ISSUE THREAD

**Issue by Misza508** [Aidurber/react-picky#103]
## Version
4.1.2 use with TypeScript
## Here's what went wrong:
I have a problem with sellect all, default is checked even when pass to the value props empty array. After select one value is unchecked and work fine. But when i pass to the props array with all selected value in opstions  sellect all is unchecked.

**Comment by Aidurber** [comment]
Can you show me a code sample? Preferably a [CodeSandbox](https://codesandbox.io)

**Comment by Misza508** [comment]
I'm solved the problem it was nothing to do with library. Issuse to close

**Comment by Aidurber** [comment]
Glad you got it sorted 🎉
