### ISSUE TITLE
issue with renderList custom function

### ISSUE THREAD

**Issue by prabhakaran-vs** [Aidurber/react-picky#104]
I want to add "Clear All" Option in list. But facing issue

  ```
renderList={({ items, selected, multiple, selectValue, getIsSelected }) =>
    this.renderCustList(items, selected, multiple, selectValue, getIsSelected)
  }
```

 ```
renderCustList(items, selected, multiple, selectValue, getIsSelected) {
        let myarray = [];
        myarray.push(
            <li >
              <strong>Clear All</strong>
            </li>
        )
        items.map(item => (
            myarray.push( <li key={item.id} onClick={() => selectValue(item)}>
              {getIsSelected(item) ? <strong>{item.name}</strong> : item.name}
            </li>
            )
          ))
          return myarray;
    }
```

**Issue**: Its rendering as expected but When i select multiple value and unselect the values one by one. list is getting closed.
Ex: if i selected 4 items, and if i unselect any one item then the list is getting closed. again i have to open the list to unselect another item.

**Expected**: It should keep open the list until i click outside.

Can someone please help me on this.

Thanks,
Prabhu

**Comment by Aidurber** [comment]
Try passing `keepOpen={true}` to your `<Picky>` component. [Prop descriptions](https://github.com/Aidurber/react-picky#prop-descriptions)

**Comment by Aidurber** [comment]
@prabhakaran-vs Did keepOpen work for you?
