### ISSUE TITLE
How to mock generateGuid for snapshot tests

### ISSUE THREAD

**Issue by mkelley33** [Aidurber/react-picky#111]
## Version
4.1.2

## Here's what went wrong:
I'm attempting to do snapshot testing of a component that uses react-picky, but the snapshots
fail to match each time they're run, because generateGuid in lib/utils is generating a new guid
in parts of the markup.  Do you know how to mock this behavior in jest or could you provide a way to get around it?

**Comment by Vadimkin** [comment]
Hi @mkelley33!

You have to mock `utils` module. Try to use it before first `describe()` method. I don't know about better solution. I also tried to create `__mocks__` directory (see [manual mocks](https://jest-bot.github.io/jest/docs/manual-mocks.html)) with mocked module and inherit all other methods, but it wasn't successful.

`Picky.test.js` (before first `describe()`):
```
jest.mock('../src/lib/utils', () => ({
  ...jest.requireActual('../src/lib/utils'),
  generateGuid: jest.fn().mockReturnValue('42'),
}));
```

You have to check that value with
```
const wrapper = mount(
  <Picky
    value={1}
    options={[1, 2, 3, 4, 5]}
    open={true}
  />
);
expect(wrapper.state('id')).toEqual('42');
```

Currently it works for all tests, but I don't know is it needed to put it to all tests or not.

Let me know please if I can help for you.

**Comment by Aidurber** [comment]
Thanks @Vadimkin 

Picky could probably worth without the generated ID, it was just for the ARIA stuff, which I know embarrassingly little about. There is perhaps a more elegant way to deal with it, maybe using refs. 🤷‍♂️

**Comment by mkelley33** [comment]
👍 thank you!
