### ISSUE TITLE
Separate styles for placeholder and selected items

### ISSUE THREAD

**Issue by pokidovea** [Aidurber/react-picky#114]
## Here's what went wrong:
The default text looks like a selected option. It would be better if the placeholder text had it's own style.

**Comment by Aidurber** [comment]
@pokidovea Do you have an example of what it should look like?

**Comment by pokidovea** [comment]
See [this](https://codesandbox.io/s/n78j6955lj), please. Default text should have a color, which shows, that it is not selected option, but just a placeholder. But when you choose an option, the text should have current color.

**Comment by Aidurber** [comment]
Released in version 4.7.1

Closed by #186

**Comment by Aidurber** [comment]
I'm just in the process of trying to improve the accessibility of Picky, and one thing that was flagged was the contrast of the placeholder. It has a contrast ratio of 2.07:1 which fails accessibility checks. 

I'm changing the placeholder colour to `#595959` which has a passing ratio of 7:1 which is AAA. 

If you want a lighter colour, by all means, override the styles in the CSS in your project. But Picky should be accessible by default.
