### ISSUE TITLE
onChange function for filter

### ISSUE THREAD

**Issue by sdei-lovepreet** [Aidurber/react-picky#118]
I have a very large list of options that is making my dropdowns hang. so, I want a onChange function for filter field, so that i can pass options to that dropdown on the basis of text in filter field.

Thanks in Advance

**Comment by Aidurber** [comment]
Happy to accept a pull request

**Comment by sdei-lovepreet** [comment]
Hello @Aidurber, I am unable to do this. can you please do this for me?

**Comment by Aidurber** [comment]
Hi @sdei-lovepreet , no, I have no interest in working on react-picky at this moment in time. I have other projects I wish to work on, as well as my job. 

If your list is very large I would recommend using the `renderList` prop with https://github.com/bvaughn/react-window so you're only rendering a subset of the data.

**Comment by sdei-lovepreet** [comment]
@Aidurber, I have found onFilterChange in react-picky's source code. but it is not working for me. can you please let me know how to use it, on typing into the filter?

**Comment by sdei-lovepreet** [comment]
Hello @Aidurber, I have forked, added functionality and created a pull request. Please merge it ASAP.

**Comment by Aidurber** [comment]
@sdei-lovepreet Also, just re-read your changes. Don't you need to return after calling `getFilterValue`? The built-in onFilterChange stuff will do its thing if you don't return.

**Comment by sdei-lovepreet** [comment]
No need of return, just keep the other stuff as it was.
Thanks for adding it.
Cheers !!!!!
