### ISSUE TITLE
Always open props for multiselect

### ISSUE THREAD

**Issue by karankumar89** [Aidurber/react-picky#127]
Is there a way by using any of the props we can force the dropdown to be always open and override any close methods. So it basically behaves like a checkbox.

**Comment by Aidurber** [comment]
`keepOpen` - Default true. Single selects close automatically when selecting a value unless this is set to true.

There is also the `open` prop, set it to true and it will always stay open.

**Comment by arokia** [comment]
But if you click outside it gets closed
