### ISSUE TITLE
(React - Picky) I have updated the library but still cannot be able to change the UI state 

### ISSUE THREAD

**Issue by Ihsan1122** [Aidurber/react-picky#132]
react-picky

If already checked
Checkbox does not change state
Note: Submitted values are correct, this is just a UI issue.

**Comment by Aidurber** [comment]
@Ihsan1122 Can you share a codesandbox or some code please?

**Comment by Ihsan1122** [comment]
@Aidurber  thanks for your response sir,

  <div>
            

                <Picky
                    options={this.state.employerTeams}
                    valueKey="_id"
                    labelKey="name"
                    value={this.state.selectedTeams}
                    multiple={true}
                    includeSelectAll={false}
                    includeFilter={true}
                    onChange={this.handleChange}
                    dropdownHeight={600}
                    render={({
                        style,
                        isSelected,
                        item,
                        selectValue,
                        labelKey,
                        valueKey,
                        multiple,
                    }) => {
                        
                        item.members.map(member => {
                            if (member.memberId === this.props.userid) {
                                isSelected = true;
                            }
                        });

                        return (
                            <li
                                style={style}
                                key={item[valueKey]} // required
                                className={isSelected ? "selected" : ""}
                            >
                                <input type="checkbox" checked={isSelected} onChange={(event) => this.props.toggleCheckboxChange(event, item, this.props.username, this.props.userid)} onClick={() => selectValue(item)} id={item[labelKey]} />
                                <label htmlFor={item[labelKey]}>{item[labelKey]}</label>
                            </li>
                        );
                    }}
                />

            </div>

**Comment by Aidurber** [comment]
@Ihsan1122 I see what you've done.

1. You're mutating the isSelected inside the render, though not necessarily an issue it shows you're bypassing the functionality of Picky. Trust Picky to handle your isSelected.
2. Call selectValue with the item `selectValue(item)`, update your state with the `onChange`. That feeds back into picky and makes sure `isSelected` is correct.
3. For selecting the item if they're the current user, do that with your component state. 

See this: https://codesandbox.io/s/w6l4v4pqz5

I hope this makes sense and is helpful Ihsan, I'm going to close this issue. Good luck!

**Comment by Ihsan1122** [comment]
@Aidurber  sir thanks for your great help.

It means a lot to me.
