### ISSUE TITLE
How to add multiple instances of react-picky?

### ISSUE THREAD

**Issue by andreeatirgovatu** [Aidurber/react-picky#136]
## Version
Latest
## Here's what went wrong:
I tried to inject two or many instances of react-picky in my code  and the selected values from the first one  are displayed in the second one. 
eg: https://codesandbox.io/s/xrom2pk98w 
How can I fix it? 

Thank you!

**Comment by Aidurber** [comment]
The `value` prop should point to a different piece of state:
```
<Picky
        value={this.state[number]}
//...
/>
```

Then your state would look like:
```
{
 1: [],
 2: []
}
```

**Comment by andreeatirgovatu** [comment]
Thank you a lot
