### ISSUE TITLE
How to clear selected value in single select?

### ISSUE THREAD

**Issue by ranjithartler** [Aidurber/react-picky#139]
## Version
"react": "^16.8.3",
"react-picky": "^4.1.2"

## Here's what went wrong:
How to clear selected value in single select? I have explored and tried but not works.

**Comment by pokidovea** [comment]
I join the question

**Comment by Aidurber** [comment]
@ranjithartler @pokidovea The same way you would with a regular HTML select, either set the value to undefined from an external event: 
https://codesandbox.io/s/simple-example-multi-and-single-select-dpgk7

Or add an option to the beginning of your items with a value of undefined: 
https://codesandbox.io/s/simple-example-multi-and-single-select-h5jex
