### ISSUE TITLE
Not getting the list of selected values on setting multiselect as true in  dynamic picky

### ISSUE THREAD

**Issue by priyankaviswan** [Aidurber/react-picky#151]
## Version
4.4.5
## Here's what went wrong:
Hi Aidurber,

I have recently downloaded the picky and have used it inside a map function to loop through my dynamic data. In the picky i have set multiselect as true. 
How ever on the onchange function am getting only the currently selected value and not the list of values selected for picky.

This is the sample code:
{
sectorsData.map((selectItem, i) => (
 <Picky value={assetsAddedState[selectItem.name]} onChange={selectedOption.bind(this,selectItem.name)} options={selectItem.options} placeholder={selectItem.name} numberDisplayed={1} valueKey="id" labelKey="name" multiple={true} includeSelectAll={true} includeFilter={true} dropdownHeight={600} className='multiSelectControl ' name={selectItem.name} />
))} 
in the on change function  i have written the following code :
   const selectedOption = (name,value) =>{
         setAssetsAddedState(prev => { return { ...prev, [name] : value}});
       }
The issue am facing is in the case of multiselect where the value will be a single object containing the current selected item rather than the list of items selected. Could you please help me with the issue. I have tried every possible solution and it does not seem to work.Any help would be really appreciated as am stuck in the issue for sometime.
Where a sample sectorsData:
[
    {
      "name": "Technology",
      "options": [
               { "id": "1",
                  "name": "AI & Analytics"
              },
              {
                  "id": "2",
                  "name": "Robotics"
              },
              {
                  "id": "3",
                  "name": "IoT"
              }
]
},
 {
      "name": "Sector",
      "options": [
         {
                  "id": "1",
                  "name": "Automotive"
              },
              {
                  "id": "2",
                  "name": "Oil and gas"
              }
]
}
]

**Comment by Aidurber** [comment]
Can you please provide a Code Sandbox, you can use this as the base: 
https://codesandbox.io/s/6o6y0

**Comment by priyankaviswan** [comment]
Hi Aidurber,
Thank you for the response,
I have used the base provided by you to share the code and please find it below.

https://codesandbox.io/embed/picky-demo-l8gpj

Also, I referred the resolved issues to see if I can get some help and found an issue similar to this #136 but its single select which works fine. In my case, it is the multi-select that is causing the issue and the issue persists

**Comment by priyankaviswan** [comment]
Hi Aidurber,
Could you please check my code base and see what's the root cause, thanks in advance
