### ISSUE TITLE
How to apply class to button only?

### ISSUE THREAD

**Issue by yoshegg** [Aidurber/react-picky#152]
I want to apply the standard bootstrap button design (`dropdown-toggle bnt btn-info`) to the button (class `picky__input`). How can I do that?

**Comment by Aidurber** [comment]
I've added a prop called buttonProps so you can pass className to the button component. It appends the class, doesn't replace it. 

### Usage
```javascript
buttonProps={{
  className: 'btn btn-info'
}}
```
