### ISSUE TITLE
Cannot get current state 

### ISSUE THREAD

**Issue by denisbykovopen** [Aidurber/react-picky#157]
## Version
latest

## Here's what went wrong:
cannot get the current state. It works only from the second one.

## Example
https://codesandbox.io/s/h6vmd

**Comment by Aidurber** [comment]
Hi @denisbykovopen, 
Not sure I completely follow, are you talking about your `console.log` in the onChange?

```
console.log("Val", value, this.state, "vals", this.state.arrayValue);
```

If so,  `setState` in React is asynchronous so you will see the current value, not the updated value in the console log. 

There is a second argument to `setState` which is called after the new state has been set:
```
this.setState({ arrayValue: value }, () => {
  console.log("Val", value, this.state, "vals", this.state.arrayValue);
});
```

**Comment by denisbykovopen** [comment]
Hello and thank you for your answer at first. And sorry for my newbie misunderstanding of the subject. 
If so, cannot you explain, or better show in example how to get the current value in your component to the state? Because i need the current array of values to work with.

**Comment by Aidurber** [comment]
You've already gotten the value: 
https://codesandbox.io/s/simple-select-dgtjq

`this.state.arrayValue` is the selected value.
