### ISSUE TITLE
Accept ID prop

### ISSUE THREAD

**Issue by coryhouse** [Aidurber/react-picky#166]
## Here's what went wrong:

I'd like to pass in an ID on props, but it's not accepted. I see the id is generated internally as a guid. But this breaks accessibility since there's no way to assign a label to this input because the ID isn't deterministic. Is there a reason the ID is generated instead of simply accepting an id as a prop?

**Comment by coryhouse** [comment]
Here's an example of an accessible label setup that isn't currently supported:

```jsx
        <label htmlFor="dealer-dropdown">Filter by Dealer</<br />
        <Picky id="dealer-dropdown"   />
```

Without accepting an id, there's no way to tie the label to the input for a11y.

**Comment by coryhouse** [comment]
I have forked this project and added this support. Happy to do a PR if you're willing to accept.

**Comment by Aidurber** [comment]
Hi @coryhouse, 
Yes, a pull request would be great!
