### ISSUE TITLE
Can we do groupBy feature using  react-picky?

### ISSUE THREAD

**Issue by bdevika** [Aidurber/react-picky#172]
## Example
Create a Code Sandbox, you can fork this: [Demo Picky](https://codesandbox.io/s/6o6y0)

**Comment by Aidurber** [comment]
No, you can do custom rendering using the render prop. Not sure how that'd work with the value. 

I'd recommend [react-select](https://github.com/JedWatson/react-select).

**Comment by bdevika** [comment]
@Aidurber , OK Thank you
