### ISSUE TITLE
How to implement lazy load and windowing with react-picky?

### ISSUE THREAD

**Issue by pravin-d** [Aidurber/react-picky#174]
Interesting take on multiselect for large sets.
Is lazy load possible with picky ? The `options` props expects the whole list.
If that is not possible how to enable windowing ? `react-window` return a <List /> component, however `renderList` props expects and array as return value.
The priority is windowing and if possible lazy loading.
Any help would appreciated

**Comment by Aidurber** [comment]
I don't see why not, I've not tested lazy loading, but it would just be a case of using the `renderList` prop. Inside that you can add your events on scroll. Then just concat the new options to the list of current options. 

The same applies for windowing/virtual lists, use the `renderList` prop.
