### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined

### ISSUE THREAD

**Issue by pardeep889** [Aidurber/react-picky#175]
## Version
latest
## Note
I am using react-picky package for showing select filter options with typescript you can check the following package.json for versions. Everything working fine when I use create-react-app without typescript. Maybe some libs got conflicted. I have tried with updating react and react-dom even it shows the same error as the image I have attached. It is not an import-export issue. I have tried every method to importing exporting.

## Package.json
```json
{
  "name": "user-portal-client",
  "version": "1.0.0",
  "description": "Front-end code for the Coinstash user portal.",
  "scripts": {
    "start": "webpack-dev-server --open",
    "start:headless": "webpack-dev-server --host 0.0.0.0 --port 5000 --watch-poll",
    "build": "webpack --config webpack.config.prod.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "@types/axios": "^0.14.0",
    "@types/classnames": "^2.2.7",
    "@types/history": "^4.7.0",
    "@types/react": "^16.4.18",
    "@types/react-dom": "^16.0.9",
    "@types/react-modal": "^3.8.1",
    "@types/react-places-autocomplete": "^7.2.3",
    "@types/react-router-dom": "^4.3.1",
    "@types/react-share": "^2.1.1",
    "@types/react-sidebar": "^3.0.0",
    "@types/socket.io-client": "^1.4.32",
    "@types/styled-components": "4.1.8",
    "@types/url-join": "^4.0.0",
    "awesome-typescript-loader": "^5.2.1",
    "copy-webpack-plugin": "^4.4.2",
    "source-map-loader": "^0.2.4",
    "styled-components": "^4.2.0",
    "ts-node": "^7.0.1",
    "typescript": "^3.5.2",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.2.1"
  },
  "dependencies": {
    "@blueprintjs/core": "^3.10.0",
    "@blueprintjs/datetime": "^3.6.0",
    "@blueprintjs/select": "^3.5.0",
    "@types/body-scroll-lock": "^2.6.1",
    "@types/reactour": "^1.13.1",
    "antd": "^3.16.3",
    "apexcharts": "^3.6.8",
    "axios": "^0.19.0",
    "body-scroll-lock": "^2.6.4",
    "classnames": "^2.2.6",
    "decimal.js": "^10.1.1",
    "mobile-detect": "^1.4.3",
    "moment": "^2.22.2",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-google-contacts": "0.0.1",
    "react-media": "^1.9.2",
    "react-modal": "^3.8.1",
    "react-picky": "^4.5.2",
    "react-places-autocomplete": "^7.2.0",
    "react-router-dom": "^4.3.1",
    "react-share": "^3.0.0",
    "react-sidebar": "^3.0.2",
    "reactour": "^1.15.0",
    "recordrtc": "^5.5.2",
    "socket.io-client": "^2.2.0",
    "url-join": "^4.0.0"
  }
}
```
## Here's what went wrong:
![react-picky](https://user-images.githubusercontent.com/25228752/63993829-e6e18c80-cb0f-11e9-9f06-13114c716047.jpeg)
`

## Example
```
import * as React from "react";
import * as ReactDOM from "react-dom";
import * as Modal from "react-modal";
import Picky from "react-picky";

declare const document: HTMLDocument;
Modal.setAppElement("#root");

const App = () => (
  <div>
    <Picky
      id="picky"
      options={[1, 2, 3, 4, 5]}
      value={[]}
      multiple={true}
      includeSelectAll={true}
      includeFilter={true}
      onChange={values => console.log(values)}
      dropdownHeight={600}
    />
    ;
  </div>
);

ReactDOM.render(<App />, document.getElementById("root"));

declare let module: any;

if (module.hot) {
  module.hot.accept();
}
```

**Comment by Aidurber** [comment]
Can you host a repository on Github reproducing this issue?

**Comment by pardeep889** [comment]
I have can only show you errors and package.json and I think its enough :)

**Comment by pardeep889** [comment]
Did you check that?

**Comment by Aidurber** [comment]
@pardeep889 I don't believe it's an issue with Picky, see this codesandbox: 
https://codesandbox.io/s/xenodochial-darkness-4kok4

It works fine until I add react-modal.

**Comment by pardeep889** [comment]
and its not working

**Comment by Aidurber** [comment]
How is it not working? I'm not getting the error you're reporting.

**Comment by pardeep889** [comment]
that is not an error I have mentioned the error above

**Comment by pardeep889** [comment]
I am closing this issue and remove this package and using this package `@syncfusion/ej2-react-dropdowns` because of no response from your side. Anyway thanks

**Comment by r-moore** [comment]
I also get this error and can reproduce it in a code sandbox.

See: https://codesandbox.io/s/hardcore-tereshkova-y60e5

Note that if you change the version of react-picky (in package.json) to 4.1.0 the error goes away - seems to be a bug in 5.x release of react-picky.

**Comment by r-moore** [comment]
Okay, it's TypeScript related. I managed to fix it in my fork by adding Picky.d.ts with a type definition for `new` inside.

(See: https://stackoverflow.com/questions/48964924/typescript-jsx-element-type-does-not-have-any-construct-or-call-signatures#48965284)

I'll be honest, I don't understand my own fix properly, but I will try to read up on it a bit and do a proper PR in a few days or so :)

**Comment by Aidurber** [comment]
@r-moore In v5, Picky is no longer a default export (some weird issue with TSDX it seemed), see: https://github.com/Aidurber/react-picky#migrations

**Comment by pardeep889** [comment]
it's very late I have used other library for that :) anyway thanks
