### ISSUE TITLE
Picky Dropdown retains the filtered list when re-opened.

### ISSUE THREAD

**Issue by Riteshgiri** [Aidurber/react-picky#178]
## version
4.5.2

## Here's what went wrong:
When you select the dropdown, type a search string on the filter and close the dropdown and open it again - the dropdown shows the filtered list with the filter previous text. The only way to get back to the original state (options) is to type in something and then manually delete it.

<img width="640" alt="Screen Shot 2019-09-23 at 5 53 32 PM" src="https://user-images.githubusercontent.com/10654768/65467563-bf8c8f80-de2f-11e9-8756-e061b3585c8b.png">

## Example
Create a Code Sandbox, you can fork this: [Demo Picky](https://codesandbox.io/s/6o6y0)

**Comment by Aidurber** [comment]
Fixed in version 4.7.0. 

Added new prop `clearFilterOnClose`

**Comment by Riteshgiri** [comment]
That works really well!!
Thanks.
