### ISSUE TITLE
Creatable picky

### ISSUE THREAD

**Issue by switz** [Aidurber/react-picky#197]
This is exactly what I'm looking for, but I need users to be able to create their own entries. Any plans to add a _create-able_ version?

e.g. https://react-select.com/creatable

**Comment by Aidurber** [comment]
Hi @switz , 
That's an interesting suggestion, I've not thought about that before, but I don't think so. 

If you use the `renderList` prop you can render the whole dropdown so you can roll your own creatable I believe.
