### ISSUE TITLE
Check "Select All" By Default in Picky

### ISSUE THREAD

**Issue by nvgopi** [Aidurber/react-picky#198]
## Version
 "react-picky": "^4.4.5"

Aidurber, 
When the app loads for the first time, I want to check the "select all" options by default. I have gone through the closed Issues but couldn't find anything. Is there a way to achieve that?

Thanks.
![Screenshot](https://user-images.githubusercontent.com/31060544/69414684-32838b00-0d39-11ea-8b8f-004023c59080.png)

**Comment by Aidurber** [comment]
You just need to provide all of your options as values when the component mounts.

Let's say you have: 
```jsx
class SomeComponent {
  componentDidMount() {
    this.setState({
      value: this.props.options
    })
  }
  render() {
    return (
      <Picky
        // Rest of props
        options={this.props.options}
        value={this.state.value}
      />
    )
  }
}
```

**Comment by nvgopi** [comment]
Thanks. That was it!
