### ISSUE TITLE
Unable to load picky.css

### ISSUE THREAD

**Issue by consciousnessdev** [Aidurber/react-picky#202]
## Version
"react-picky": "^5.2.0"

## Here's what went wrong:
when start apps, it generate
"Error: undefined Unable to resolve module `react-picky/dist/picky.css` from `src/...`"

## Screenshoot
i've done do this but it still happen
![Image of step to resolve](https://i.imgur.com/3Ag7E2gl.png)

**Comment by Aidurber** [comment]
@consciousnessdev Picky doesn't work in React Native
