### ISSUE TITLE
class `picky_placeholder` is reversed from version 4.x

### ISSUE THREAD

**Issue by martinwaugh** [Aidurber/react-picky#203]
## Version

5.2.0 (starting in 5.0.2)

## Here's what went wrong:

In version 4.7.x (and 5.0.1), the `picky_placeholder` class was applied when the selection was empty, and not otherwise. Now it is the reverse.

## Example

![image](https://user-images.githubusercontent.com/16947443/75068923-fa5d2700-54a4-11ea-99ad-f441468573fc.png)

**Comment by Aidurber** [comment]
@martinwaugh Thanks for reporting this one, I'm sorry about this regression. I've added tests to ensure this doesn't happen again.
