### ISSUE TITLE
Would like to have a singleSelectedPlaceholder

### ISSUE THREAD

**Issue by mcusack60** [Aidurber/react-picky#216]
## Version
current
## Here's what went wrong:
Similar to how you have the manySelectedPlaceholder and allSelectedPlaceholder, it would be nice to have a singleSelectedPlaceholder to override the default behavior of displaying the selected value when the picky is not a multi-select.

## Example
Create a Code Sandbox, you can fork this: [Demo Picky](https://codesandbox.io/s/6o6y0)

**Comment by Aidurber** [comment]
@mcusack60 I'm sorry for the late reply, I've been extremely busy with work and not coding in my evenings. I'll try and get around to this in the next couple of days. This seems like a decent suggestion.

**Comment by Aidurber** [comment]
@mcusack60 This should now be on NPM in v5.3.0
