### ISSUE TITLE
Picky is focused twice when navigating using tab button.

### ISSUE THREAD

**Issue by czeslaaw** [Aidurber/react-picky#221]
## Version
5.3.0

## Here's what went wrong:
When navigating using tab focus is set twice on Picky: first on the div wrapper and then on the button. Likely tabindex should be on the button and not on the wrapper.

## Example
(https://codesandbox.io/s/6o6y0)

Just use tab to navigate demo above.

**Comment by Aidurber** [comment]
@czeslaaw Thanks for the report and the solution to it!
