### ISSUE TITLE
maxLength on filter input

### ISSUE THREAD

**Issue by fishonweb** [Aidurber/react-picky#226]
I would like to be able to limit character in filter input.

Currently, any user could type character in input filter without limit. It could be useful to use maxLength to limit it.

**Comment by Aidurber** [comment]
Hmm, perhaps by using the `filterTermProcessor` see here: https://github.com/Aidurber/react-picky#prop-descriptions

>  A function that takes a string and returns a string. Useful for trimming and processing a filter term before it filters the options. Default: (term) => term

Your function could be something like: `(term) => term.trim().slice(0, 20)`

**Comment by fishonweb** [comment]
Thank you !
I had tried it and I have error with react minification with Version 5. I have to fix it to valid this.

**Comment by Aidurber** [comment]
@fishonweb Did you figure it out?
