### ISSUE TITLE
Is it possible to close the dropdown after selection if using a single select

### ISSUE THREAD

**Issue by mgpGit** [Aidurber/react-picky#227]
## Version
    "^5.3.2"

## Here's what went wrong:

If using single select, is it possible to close the dropdown after selection? 

I tried setting the "open" option to false onChange(), but that property only seems to work onload.

This would be helpful as otherwise it seems odd to have to click off to close the dropdown after you select a single item.

Thoughts?

## Example
Create a Code Sandbox, you can fork this: [Demo Picky](https://codesandbox.io/s/6o6y0)

**Comment by Aidurber** [comment]
@mgpGit set the `keepOpen` prop to false. See [README](https://github.com/Aidurber/react-picky#prop-descriptions) 

> keepOpen - Default true. Single selects close automatically when selecting a value unless this is set to true.

It only works for single select mode, not multiple select mode. 

See this [demo](https://codesandbox.io/s/small-smoke-747ve?file=/src/App.js)

**Comment by mgpGit** [comment]
Perfect! Thanks!
