### ISSUE TITLE
dropdownHeight should set max-height instead of height

### ISSUE THREAD

**Issue by rheinheimer** [Aidurber/react-picky#26]
## Version
1.5.1
## Here's what went wrong:
dropdownHeight prop sets "height", not "max-height", so that few options results in extra dropdown space.

p.s. thanks for this!!! I had the exact same problem this is trying to solve. It's a great start, and I imagine it will become quite used. A couple more issues forthcoming...

**Comment by Aidurber** [comment]
Hi @rheinheimer, thanks for the issues. 

Height isn't actually set to the dropdown menu, it's set to the VirtualList from [react-tiny-virtual-list](https://github.com/clauderic/react-tiny-virtual-list#example-usage) which creates the height. 

I can see the issue. 

The only alternative I can see is to swap out [react-tiny-virtual-list](react-tiny-virtual-list) for [react-virtualized](https://github.com/bvaughn/react-virtualized) specifically for [AutoSizer](https://github.com/bvaughn/react-virtualized/blob/master/docs/AutoSizer.md)

I'll take a look. 
P.S. Thank you for the kind words and thanks for the issues!

**Comment by rheinheimer** [comment]
Another option could be to pass on this need to react-tiny-virtual-list, but react-virtualized looks pretty solid.

**Comment by Aidurber** [comment]
Another option would be to remove virtual lists completely. The developer can use a render prop with a virtual list if they needed a performance gain with a particularly large list. 

I'll give react-virtualized a look to see if I can get it to play nice. But removing them isn't off the table.

**Comment by Aidurber** [comment]
@rheinheimer After playing around with react-virtualized, it's not possible to dynamically size the virtual list height based on children. 

You can however use a container height. AutoResizer from RV can pass a height prop which is taken from the DOM container the component is positioned in. I don't believe it fill pleasantly fix the issue you're describing. 

I could however add a prop that the developer can set to false to disable the virtual list: 
 - virtual - Boolean (default: true) - Disables virtual list. 

Which would leave you with an "organic" list with a more flexible height.

**Comment by Aidurber** [comment]
@rheinheimer if you pass `virtual={false}` you won't get a virtual list but the plain list will use min-height for dropdown height.

**Comment by rheinheimer** [comment]
@Aidurber nice, perfect!
