### ISSUE TITLE
Additional prop for x selected 

### ISSUE THREAD

**Issue by Aidurber** [Aidurber/react-picky#29]
An additional prop, not sure on the name, maybe `manyDisplayedPlaceholder`.

Not sure if a render prop or a sprintf style  input like:
```
"You have selected %s" 
```

The render prop would be called with the number of selected items.

Leaning towards the latter.

**Comment by AndreBastos23** [comment]
Yes that would suffice.
Do you think its possible to have maybe a prop that instead of saying "X selected" when all are selected, just says another string? For example "All" or something.

**Comment by Aidurber** [comment]
Yes, since it will be a sprintf style input you could have whatever you want. The API will look like so: 
`manyDisplayedPlaceholder="Whatever"`

If you want the number of items selected: 
`manyDisplayedPlaceholder="That's %s items selected"`

It would be worth adding yet another prop `allSelectedText` which is shown when all items are selected. 

No items selected: `placeholder` OR "None selected" (default)
Some items selected and <= `numberDisplayed`: "Item 1, Item 2"
Some items selected and > `numberDisplayed`: `manyDisplayedPlaceholder` OR "x selected" (default)
All selected: `allSelectedText` OR "x selected" (default)

**Comment by AndreBastos23** [comment]
Yeah that would be perfect :)
