### ISSUE TITLE
IE 11 Compatibility

### ISSUE THREAD

**Issue by AndreBastos23** [Aidurber/react-picky#32]
Hello,

Your library does not work with IE11.
I traced the problem to the "includes" method that you use when verifying the placeholder props. IE11 does not recognize that method. Is it possible to swap to a polyfill alternative?

**Comment by Aidurber** [comment]
Yes that's possible. Good find, I thought my babel config took care of that, apparently not. Thanks for reporting.

**Comment by AndreBastos23** [comment]
If you dont want to change that much code, you can paste the following code on your entry react component. That's what i did to fix this.

`
if (!String.prototype.includes) {
    String.prototype.includes = function (search, start) {
        if (typeof start !== 'number') {
            start = 0;
        }
        if (start + search.length > this.length) {
            return false;
        } else {
            return this.indexOf(search, start) !== -1;
        }
    };
}`

That basically creates the prototype "includes" if it doesnt exist..

**Comment by Aidurber** [comment]
@AndreBastos23 decided to use lodash.includes, that fixes the `Array.prototype.includes` issue in IE11 too. 

Sorry about that, fixed in 1.7.1 which is on npm now.
