### ISSUE TITLE
Placeholder Strings

### ISSUE THREAD

**Issue by AndreBastos23** [Aidurber/react-picky#33]
Following the last issue i opened (#29) regarding the placeholder, there is some more strings that are hard-coded.
They are:

- Select all(should be a prop?)
- None Selected(prop again?)

This way, everyone can use your component in whatever language they need, or using any strings they want.

**Comment by Aidurber** [comment]
Hi @AndreBastos23 , 
Thanks for the issue. 
1. Sorry, I missed that one. Will add a prop now. 
2. "None selected" is the `placeholder` prop default. You can override that already.
