### ISSUE TITLE
Make number of selected items dynamically

### ISSUE THREAD

**Issue by AndreBastos23** [Aidurber/react-picky#35]
Is it possible to make the number of selected items necessary to show the message "X selected numbers" dynamic? that is, having a prop that decides what that number should be?

**Comment by Aidurber** [comment]
@AndreBastos23 can you give me an example? What number would you like it to be?

**Comment by Aidurber** [comment]
You can pass in any placeholder you wish: [Dynamic placeholder example](https://codesandbox.io/s/mq6n2zv42x)

See the above example, it's a little contrived but lets say I want a placeholder that shows the number of items that have an even ID. 

There doesn't need to be another prop for this I don't think.

**Comment by AndreBastos23** [comment]
I might be wrong, but right now you only show the "X items selected" placeholder when you have 3 or more items selected.. What if i wanted to show this message with only 1 item selected?

**Comment by Aidurber** [comment]
Yep, that's the prop :smiley:

**Comment by Aidurber** [comment]
Yep, that's the prop :smiley:
