### ISSUE TITLE
initialValue problem

### ISSUE THREAD

**Issue by floorswinkels** [Aidurber/react-picky#39]
## Here's what went wrong: 
1. Put an initial array in prop value.
2. Next deselect an initial item gives an good onChange result. ( initial array minus 1 )
3. Reset 
4. Put an initial array in prop value.
5. Select an new extra item gives a bad onChange result. ( only the selected item without initial array values )

**Comment by Aidurber** [comment]
Hi @floorswinkels 

Thanks for raising this issue, though I'm unable to replicate. 

Could you please create a [CodeSandbox](https://codesandbox.io) reproducing the issue. 

You can fork this one if that makes it easier: 
https://codesandbox.io/s/0p3oxq3150

**Comment by floorswinkels** [comment]
I can't replicate it in codeSandbox,
but i think I found the problem.

The picky constructor is called before I have the initial data.

Could this cause the problem ?

**Comment by Aidurber** [comment]
Ahh great assessment. I can replicate now. I'll take a look!

**Comment by Aidurber** [comment]
@floorswinkels That should now be published. 

I hopefully got the release right, semantic-release was playing up and I ended up publishing version 0.0.0 😁 

Again, thanks for reporting the issue ⭐️

**Comment by floorswinkels** [comment]
thanks @Aidurber 

It's working now with version 1.9.1 !

**Comment by Aidurber** [comment]
@floorswinkels Glad to hear it, thanks for letting me know!
