### ISSUE TITLE
Allow customizing using styled-components

### ISSUE THREAD

**Issue by pimtel** [Aidurber/react-picky#41]
Hi,

Would be very useful if we could pass a custom class for the component, for the sake to customize it using, for example, styled-component. Currently, it keeps only `.picky' class

```javascript
import Picky from 'react-picky'
import styled from 'styled-components'

const Select = styled(Picky)`
   background-color: grey
`
```
Currently, as I mentioned, `className` is fixed
```javascript
<div
  ref={node => {
    this.node = node;
  }}
  className="picky" />
```
It could be something like that:
```javascript
className={[className, 'picky']}
```

Best regards

**Comment by Aidurber** [comment]
@rgercp Great idea, I'll see what I can do when I finish work today. 👍

**Comment by Aidurber** [comment]
Release 1.10.0 is available now. 

The support is pretty basic, but it should do:
```javascript
const Select = styled(Picky)`
  background-color: #ff0000;
  .picky__dropdown,
  .option {
    font-size: 2em;
  }
`;
```
