### ISSUE TITLE
Disable options

### ISSUE THREAD

**Issue by karankumar89** [Aidurber/react-picky#63]
Hello!

I've been playing around with certain ideas with the options and i was wondering if there is a way to disable certain options?

Thanks,
Karan Kumar

**Comment by Aidurber** [comment]
Hi @karankumar89 

I would use the render prop to render custom list items then disable them as needed. On your array of items you can add a disabled property and reference that: 

```javascript
 <Picky 
  {...restOfYourProps}
  render={({
    style,
    isSelected,
    item,
    selectValue,
    labelKey,
    valueKey,
    multiple
  }) => {
    const cssClass = classNames({ disabled: item.disabled, selected: isSelected })
    return (
      <li
        style={style} // required
        className={cssClass} // required to indicate is selected
        key={item[valueKey]} // required
        onClick={() => selectValue(item)}
      >
        {/* required to select item */}
        <input type="checkbox" checked={isSelected} readOnly disabled={item.disabled} />
        <span style={{ fontSize: '30px' }}>{item[labelKey]}</span>
      </li>
    );
  }}
/>
```

The example uses: https://www.npmjs.com/package/classnames

I've not tested the above code but it should put you on the right track. I hope this helps 👍
