### ISSUE TITLE
MutiSelect checkboxes clicking not working properly

### ISSUE THREAD

**Issue by arun567** [Aidurber/react-picky#76]
## Version
2.0.5

## Here's what went wrong:

In MutiSelect, When I Click on any of checkbox it is hitting onChange two times. Due to this if I write an API calling in onChange method then it is firing two times. Instead of clicking on checkbox if I click on lable in <**li**> then it is working fine.

**Comment by Aidurber** [comment]
Hi @arun567 
Weird bug but I can replicate, I'll take a look. 
Thanks for raising!

**Comment by arun567** [comment]
Hi Andrew Durber,

Bug still exist when you select and deselect "All" option.I mean when includeSelectAll={true}
