### ISSUE TITLE
Object options with valueKey is not working

### ISSUE THREAD

**Issue by misterbridge** [Aidurber/react-picky#79]
## Version
3.0.2

## Here's what went wrong:
Setting an array of objects as `options` with a `valueKey` to define wich key are the values and setting an array of `value` doesnt work (none get checked)
There is a least a bug in :
```javascript
  isItemSelected(item) {
    [...]
    return hasItem(value, item, this.props.labelKey, this.props.valueKey);
  }
```
because `hasItem` has the 2 last arguments reversed (`valueKey` THEN `labelKey`):
```javascript
export const hasItem = (all, item, valueKey, labelKey, returnIndex) => {
  [...]
});
```

But setting `valueKey` and `labelKey` as the options' label and `value` as an array of options' values doest work either, so there is also another bug somewhere.

**Comment by Aidurber** [comment]
Hi @misterbridge 
Good spot on the isItemSelected. 

I'm unable to understand what you mean with your issue? Can you give me a code example please?

**Comment by misterbridge** [comment]
Hey @Aidurber,
As of the bug on isItemSelected I tried with switching `valueKey` and `labelKey` in my props but it was still not working.
I guess all I ask for is, when you'll fix the isItemSelected bug, try using it (an object as `options` + a `valueKey` + a `labelKey`) to be sure it works.

Thanks for this component, it's really nice !

**Comment by Aidurber** [comment]
@misterbridge 
See: https://codesandbox.io/s/747z71zpxj

That is using an array of objects with the labelKey and value key, it's working. 
Try version 4 and let me know if you're still having the same issue. If you are can you provide me with some code?

Thank you :)

**Comment by misterbridge** [comment]
Looks like it works, thanks !
