### ISSUE TITLE
"Select all" checkbox is not checked when all the items are selected

### ISSUE THREAD

**Issue by erokhin74** [Aidurber/react-picky#94]
## Version
4.1.1
## Here's what went wrong:
Initial state: There are 2 items in the list and select-all-checkbox, all the items are selected and select-all-checkbox is checked.
1. Unselect FIRST item, select-all-checkbox is unchecked. It is correct.
2. Select FIRST item again, select-all-checkbox is unchecked. It is incorrect - select-all-checkbox should be checked.

At selecting/unselecting the second (last) item, the select-all-checkbox works correctly.

I tried in the sandbox https://codesandbox.io/s/mmpq6z7lr8
with slice(0, 2) in the getCountries().

**Comment by Aidurber** [comment]
@erokhin74 Make sure you're using a React version higher than 16.3.0. I'll update the existing codesandboxes.

**Comment by erokhin74** [comment]
My current React version is "16.4.2". It is higher than 16.3.0.

**Comment by randymorris** [comment]
I think there are potentially two issues here.

First, in `Picky.UNSAFE_componentWillReceiveProps`, the assumption is made that if the `props.value` is the same between current and next props, then the set of props is equal.  It doesn't consider that `props.options` may differ.

Second, in `Picky.allSelected` - again, only the value is considered.

I think that if we were to check both options and value in both cases this probably is probably fixed.  This would mean passing an additional `overrideOptions` to `Picky.allSelected`.

Something like the following maybe:

```diff
diff --git a/src/Picky.js b/src/Picky.js
index e00efd9..dfed65d 100644
--- a/src/Picky.js
+++ b/src/Picky.js
@@ -58,13 +58,15 @@ class Picky extends React.PureComponent {
       this.props.options !== nextProps.options ||
       this.props.value !== nextProps.value
     ) {
-      let areEqual = Array.isArray(nextProps.value)
+      let valuesEqual = Array.isArray(nextProps.value)
         ? arraysEqual(nextProps.value, this.props.value)
         : nextProps.value === this.props.value;
 
+      let optsEqual = arraysEqual(nextProps.options, this.props.options);
+
       this.setState({
-        allSelected: !areEqual
-          ? this.allSelected(nextProps.value)
+        allSelected: !(valuesEqual && optsEqual)
+          ? this.allSelected(nextProps.value, nextProps.options)
           : this.allSelected(),
       });
     }
@@ -119,15 +121,16 @@ class Picky extends React.PureComponent {
    * @returns {Boolean}
    * @memberof Picky
    */
-  allSelected(overrideSelected) {
+  allSelected(overrideSelected, overrideOptions) {
     const { value, options } = this.props;
     const selectedValue = overrideSelected || value;
+    const selectedOptions = overrideOptions || options;
 
     // If there are no options we are getting a false positive for all items being selected
-    if (options && options.length === 0) {
+    if (selectedOptions && selectedOptions.length === 0) {
       return false;
     }
-    let copiedOptions = options.map(this.getValue);
+    let copiedOptions = selectedOptions.map(this.getValue);
     let copiedValues = Array.isArray(selectedValue)
       ? selectedValue.map(this.getValue)
       : [];
```

**Comment by randymorris** [comment]
After some more thinking about this specific issue, I think I've figured out why this happens.

Whenever the select all state is checked, order of options and values is expected to be the same.  However, whenever an item is added to the values it is added to the end of the list.  Thus, if we have options = `[1, 2, 3]` and values = `[1, 2, 3]` the select all state would be correct.  If we uncheck `1`, then recheck `1`, the values would be `[2, 3, 1]` which no longer matches the options.

This also explains why the last value in the list doesn't exhibit this behavior, because it's already at the end of the list.
