### ISSUE TITLE
More styling control for picky__input (trigger button).

### ISSUE THREAD

**Issue by alturium** [Aidurber/react-picky#96]
## Version
4.1.2
## Here's what went wrong:
Would like to control the css style of the button classname="picky__input" such as when the dropdown is opened, the background color is changed.  Motivation: using Atlaskit and Reactstrap, but fall short for long dropdown lists (checkboxes), and need to use their style for the Picky component.

Possible solutions:
- Add prop for triggerButtonProps for trigger button.  Or classname prop for trigger button.
- Perhaps there is a way to extend with Styled and CSS selectors and set picky classnames (tried but I could not get this to work.  Idea would be to add open|close to Picky classnames, and have CSS selector to change style since button is a child of 'picky'.

**Comment by justin22** [comment]
@Aidurber Is there any way to control the background color/border-color of the checkbox/radio when selected?

**Comment by Aidurber** [comment]
@alturium Happy to accept a PR for that. 

@justin22 I'd recommend using a render prop, see [Custom Rendering](https://github.com/Aidurber/react-picky#custom-rendering-1)

You can use render props for: 
 - Select all
 - Individual options
 - The whole list


If you need to go further than that [Downshift](https://github.com/downshift-js/downshift) is super flexible.

**Comment by Aidurber** [comment]
@alturium You should be able to do this now, there is a prop called `buttonProps` these simply get merged into the button component. Any className supplied get merged. 
```
<Picky 
 buttonProps={{
 className: "some-custom-classname"
}}
/>
```
